export const LEVELS: Record<string, string> = {
    l01_escape:            'Cordon',
    l02_garbage:           'Garbage',
    l03_agroprom:          'Agroprom',
    l03u_agr_underground:  'Agroprom Underground',
    l04_darkvalley:        'Dark Valley',
    l04u_labx18:           'Lab X-18',
    l05_bar:               'Rostok',
    l06_rostok:            'Wild Territory',
    l07_military:          'Army Warehouses',
    l08_yantar:            'Yantar',
    l09_deadcity:          'Dead City',
    l10_limansk:           'Limansk',
    l10_radar:             'Radar',
    l10_red_forest:        'Red Forest',
    l10u_bunker:           'X-19 Bunker',
    l11_pripyat:           'Pripyat (SoC)',
    l11u_hospital:         'Hospital',
    l11u_sarcofag:         'Sarcophagus',
    l12_stancia:           'Chernobyl NPP',
    l12u_control_monolith: 'Control Monolith',
    l12u_sarcofag:         'Sarcophagus Interior',
    l13_generators:        'Generators',
    l16_military:          'Military Underground',
    l18_swamp:             'Swamps',
    l19_marsh:             'Marsh',
    labx8:                 'Lab X-8',
    jupiter:               'Jupiter',
    zaton:                 'Zaton',
    pripyat:               'Pripyat',
    k00_marsh:             'Great Swamps',
    k01_darkscape:         'Darkscape',
    k02_trucks_cemetery:   'Truck Cemetery',
    y04_pole:              'Meadow',
}

export const FACTIONS: Record<string, string> = {
    stalker: 'Loner', actor_stalker: 'Loner', bandit: 'Bandit', army: 'Military', freedom: 'Freedom',
    duty: 'Duty', ecolog: 'Ecologist', csky: 'Clear Sky', monolith: 'Monolith',
    actor: 'Loner', independent: 'Independent', killer: 'Mercenary',
}

export const FACTION_COLORS: Record<string, string> = {
    stalker: '#4a9eff', actor_stalker: '#4a9eff', bandit: '#e8a838', army: '#5cb85c', freedom: '#9b59b6',
    duty: '#e74c3c', ecolog: '#1abc9c', csky: '#3498db', monolith: '#8e44ad',
    actor: '#4a9eff', killer: '#e67e22',
}

export const FACTION_ICONS: Record<string, string> = {
    stalker: '/factions/faction_loners.png', actor_stalker: '/factions/faction_loners.png',
    actor: '/factions/faction_loners.png',
    bandit: '/factions/faction_bandits.png',
    army: '/factions/faction_military.png',
    freedom: '/factions/faction_freedom.png',
    duty: '/factions/faction_duty.png',
    ecolog: '/factions/faction_ecologists.png',
    csky: '/factions/faction_clearsky.png',
    monolith: '/factions/faction_monolith.png',
    killer: '/factions/faction_mercenary.png',
    independent: '/factions/faction_inisig.png',
}

export const DEATH_LINES = [
    'The Zone claims another stalker.',
    "Should've brought more medkits.",
    'Every stalker meets the Zone eventually.',
    "The Zone doesn't forgive mistakes.",
    'One wrong step.',
    'Suit up. Try again.',
    'You pushed too far.',
    'Better luck next run, stalker.',
    'The anomalies had the last word.',
    'Even legends bleed.',
    'The Zone is unforgiving.',
    'Another name for the memorial wall.',
    "Rookie mistake. Won't happen again.",
    'Death comes for us all out here.',
    'The Zone giveth, the Zone taketh.',
]
