export const LEVELS: Record<string, string> = {
	l01_escape: 'Cordon',
	l02_garbage: 'Garbage',
	l03_agroprom: 'Agroprom',
	l03u_agr_underground: 'Agroprom Underground',
	l04_darkvalley: 'Dark Valley',
	l04u_labx18: 'Lab X-18',
	l05_bar: 'Rostok',
	l06_rostok: 'Wild Territory',
	l07_military: 'Army Warehouses',
	l08_yantar: 'Yantar',
	l09_deadcity: 'Dead City',
	l10_limansk: 'Limansk',
	l10_radar: 'Radar',
	l10_red_forest: 'Red Forest',
	l10u_bunker: 'X-19 Bunker',
	l11_pripyat: 'Pripyat (SoC)',
	l11u_hospital: 'Hospital',
	l11u_sarcofag: 'Sarcophagus',
	l12_stancia: 'Chernobyl NPP',
	l12u_control_monolith: 'Control Monolith',
	l12u_sarcofag: 'Sarcophagus Interior',
	l13_generators: 'Generators',
	l16_military: 'Military Underground',
	l18_swamp: 'Swamps',
	l19_marsh: 'Marsh',
	labx8: 'Lab X-8',
	jupiter: 'Jupiter',
	zaton: 'Zaton',
	pripyat: 'Pripyat',
	k00_marsh: 'Great Swamps',
	k01_darkscape: 'Darkscape',
	k02_trucks_cemetery: 'Truck Cemetery',
	y04_pole: 'Meadow',
};

export const FACTIONS: Record<string, string> = {
	stalker: 'Loner',
	actor_stalker: 'Loner',
	actor: 'Loner',
	bandit: 'Bandit',
	army: 'Military',
	military: 'Military',
	freedom: 'Freedom',
	duty: 'Duty',
	ecolog: 'Ecologist',
	csky: 'Clear Sky',
	monolith: 'Monolith',
	killer: 'Mercenary',
	renegade: 'Renegade',
	mutant: 'Mutant',
	helicopter: 'Helicopter',
	other: 'Other',
	independent: 'Independent',
	greh: 'Sin',
	sin: 'Sin',
};

// Faction text/label colors — from Figma Faction Icon component set
export const FACTION_COLORS: Record<string, string> = {
	stalker: '#e8c46a',
	actor_stalker: '#e8c46a',
	actor: '#e8c46a',
	bandit: '#c87a3a',
	army: '#6a9e6a',
	military: '#6a9e6a',
	freedom: '#5a8ab4',
	duty: '#c85a5a',
	ecolog: '#8ab45a',
	csky: '#5ab4b4',
	monolith: '#9a7ab4',
	killer: '#c8a85a',
	renegade: '#b4b45a',
	mutant: '#c85a5a',
	helicopter: '#c8a85a',
	other: '#8a8070',
	independent: '#8a8070',
	greh: '#c8954a',
	sin: '#c8954a',
};

// Icon background colors — from Figma Faction Icon component fills
export const FACTION_BG_COLORS: Record<string, string> = {
	stalker: '#3a2c08',
	actor_stalker: '#3a2c08',
	actor: '#3a2c08',
	bandit: '#3a2010',
	army: '#1a3a20',
	military: '#1a3a20',
	freedom: '#152438',
	duty: '#3a1212',
	ecolog: '#1e2e0a',
	csky: '#0f2e2e',
	monolith: '#25143a',
	killer: '#1a1a3a',
	renegade: '#2a2a0e',
	mutant: '#3a1212',
	greh: '#2a1a08',
	sin: '#2a1a08',
};

export const FACTION_ICONS: Record<string, string> = {
	stalker: '/factions/faction_loners.webp',
	actor_stalker: '/factions/faction_loners.webp',
	actor: '/factions/faction_loners.webp',
	bandit: '/factions/faction_bandits.webp',
	army: '/factions/faction_military.webp',
	military: '/factions/faction_military.webp',
	freedom: '/factions/faction_freedom.webp',
	duty: '/factions/faction_duty.webp',
	ecolog: '/factions/faction_ecologists.webp',
	csky: '/factions/faction_clearsky.webp',
	monolith: '/factions/faction_monolith.webp',
	killer: '/factions/faction_mercenary.webp',
	renegade: '/factions/faction_renegades.webp',
	independent: '/factions/faction_inisig.webp',
	greh: '/factions/faction_sin.webp',
	sin: '/factions/faction_sin.webp',
	mutant: '/factions/faction_mutant.webp',
};
